-- Fictional reference data only. This seed intentionally avoids creating
-- login accounts until a local bcrypt hash can be generated by the backend.
USE openclinic_db;

INSERT INTO roles (role_name) VALUES
  ('ADMIN'), ('DOCTOR'), ('RECEPTIONIST'), ('PATIENT')
ON DUPLICATE KEY UPDATE role_name = VALUES(role_name);

INSERT INTO departments (name, description) VALUES
  ('Family Medicine', 'Fictional demonstration department'),
  ('Dermatology', 'Fictional demonstration department'),
  ('Pediatrics', 'Fictional demonstration department')
ON DUPLICATE KEY UPDATE description = VALUES(description);

INSERT INTO medicines (name, description) VALUES
  ('Demo Medicine A', 'Fictional catalog item for software demonstrations'),
  ('Demo Medicine B', 'Fictional catalog item for software demonstrations'),
  ('Demo Medicine C', 'Fictional catalog item for software demonstrations')
ON DUPLICATE KEY UPDATE description = VALUES(description);
